apiVersion: v1
kind: Service
metadata:
  name: v1-mini_ui-svc
  namespace: hawk
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: mini-ui
    type: ui
    tag: 0.1.0-v1
  sessionAffinity: None
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: v1-mini-ui
  namespace: hawk
  labels:
    tag: 0.1.0-v1
    app: mini-ui
    type: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      tag: 0.1.0-v1
      app: mini-ui
      type: ui
  template:
    metadata:
      labels:
        tag: 0.1.0-v1
        app: mini-ui
        type: ui
    spec:
      containers:
      - image: immnan/mini-ui:0.1.1
        imagePullPolicy: IfNotPresent
        name: mini-ui
        env:
        - name: RAG_BASE_URL
          value: v1-orca-svc
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
          name: http

        resources:

          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: 250m
            memory: 512Mi