/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as ApiV1RagGoRouteImport } from './routes/api.v1.rag-go'
import { Route as ApiV1RagGoGenerateDocRouteImport } from './routes/api.v1.rag-go.generate-doc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RagGoRoute = ApiV1RagGoRouteImport.update({
  id: '/api/v1/rag-go',
  path: '/api/v1/rag-go',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RagGoGenerateDocRoute = ApiV1RagGoGenerateDocRouteImport.update({
  id: '/generate-doc',
  path: '/generate-doc',
  getParentRoute: () => ApiV1RagGoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/v1/rag-go': typeof ApiV1RagGoRouteWithChildren
  '/api/v1/rag-go/generate-doc': typeof ApiV1RagGoGenerateDocRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/v1/rag-go': typeof ApiV1RagGoRouteWithChildren
  '/api/v1/rag-go/generate-doc': typeof ApiV1RagGoGenerateDocRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/v1/rag-go': typeof ApiV1RagGoRouteWithChildren
  '/api/v1/rag-go/generate-doc': typeof ApiV1RagGoGenerateDocRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products/$productId'
    | '/api/v1/rag-go'
    | '/api/v1/rag-go/generate-doc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products/$productId'
    | '/api/v1/rag-go'
    | '/api/v1/rag-go/generate-doc'
  id:
    | '__root__'
    | '/'
    | '/products/$productId'
    | '/api/v1/rag-go'
    | '/api/v1/rag-go/generate-doc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ApiV1RagGoRoute: typeof ApiV1RagGoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rag-go': {
      id: '/api/v1/rag-go'
      path: '/api/v1/rag-go'
      fullPath: '/api/v1/rag-go'
      preLoaderRoute: typeof ApiV1RagGoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rag-go/generate-doc': {
      id: '/api/v1/rag-go/generate-doc'
      path: '/generate-doc'
      fullPath: '/api/v1/rag-go/generate-doc'
      preLoaderRoute: typeof ApiV1RagGoGenerateDocRouteImport
      parentRoute: typeof ApiV1RagGoRoute
    }
  }
}

interface ApiV1RagGoRouteChildren {
  ApiV1RagGoGenerateDocRoute: typeof ApiV1RagGoGenerateDocRoute
}

const ApiV1RagGoRouteChildren: ApiV1RagGoRouteChildren = {
  ApiV1RagGoGenerateDocRoute: ApiV1RagGoGenerateDocRoute,
}

const ApiV1RagGoRouteWithChildren = ApiV1RagGoRoute._addFileChildren(
  ApiV1RagGoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ApiV1RagGoRoute: ApiV1RagGoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
